import {
  COLOR_BLACK,
  COLOR_CORAL,
  COLOR_GREY,
  COLOR_LIGHT_BLACK,
  COLOR_PEACH,
  COLOR_PINK,
  COLOR_SKIN,
  COLOR_SKY_BLUE,
  COLOR_TEAL,
  COLOR_TURTOISE,
  COLOR_WHITE,
} from './colorConstants';

export default {
  COLOR_PRIMARY: COLOR_SKY_BLUE,
  COLOR_SECONDARY: COLOR_LIGHT_BLACK,
};
