import {
  COLOR_BLACK,
  COLOR_CORAL,
  COLOR_GREY,
  COLOR_LIGHT_BLACK,
  COLOR_PINK,
  COLOR_SKIN,
  COLOR_TEAL,
  COLOR_TURTOISE,
  COLOR_WHITE,
} from './colorConstants';

export default {
  COLOR_PRIMARY: COLOR_PINK,
  COLOR_SECONDARY: COLOR_LIGHT_BLACK,
  COLOR_LIGHT_SECONDARY: COLOR_TURTOISE,

  COLOR_TERTIARY: COLOR_GREY,
  COLOR_BLACK: COLOR_BLACK,
  COLOR_WHITE: COLOR_WHITE,
  COLOR_SKIN: COLOR_SKIN,
};
